version: '3'
services:
  frontend:
    build: .
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
    volumes:
      - .:/usr/src/app

  backend:
    build: backend
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - backend:/usr/src/app

volumes:
  backend:
